### ISSUE TITLE
Melhorias para as Ordens de Serviço

### ISSUE THREAD

**Issue by brtechst** [hoshikawakun/MasterOS#10]
Acredito ser a maioria dos usuários da área de tecnologia que usa Mapos, então creio que será de grande utilidade para a maioria se não todos:

Na tela de cadastro ou edição das OS deveria ter mais campos fixos para preenchimento dos dados dos equipamentos e justamente esses dados ficarem gravados na cartela de cada cliente para futuras consultas ou futuras OS para os mesmo equipamentos ja não iria precisar ter que digitar tudo de novo.

![image](https://user-images.githubusercontent.com/53625745/116604333-5c64b800-a904-11eb-8dbe-b0816e1a2c96.png)

Campos necessários:

EQUIPAMENTO: 
MARCA:  Isso ja tem lá
MODELO:  
NÚMERO DE SÉRIE:  ja tem lá
PROCESSADOR: 
PLACA DE VÍDEO:  
RAM:
HD / SSD: 
SISTEMA OPERACIONAL: 
SERIGRAFIA DA PLACA MÃE: 
TEM SENHA?: 
PRECISA DE BACKUP?: 
DEIXOU ALGUM ACESSÓRIO?: 

Esse campo Descrição Produto/Serviço poderia ser desabilitado com essas opções ou deixa ele ai sem uso.

**Comment by hoshikawakun** [comment]
> 
> 
> Acredito ser a maioria dos usuários da área de tecnologia que usa Mapos, então creio que será de grande utilidade para a maioria se não todos:
> 
> Na tela de cadastro ou edição das OS deveria ter mais campos fixos para preenchimento dos dados dos equipamentos e justamente esses dados ficarem gravados na cartela de cada cliente para futuras consultas ou futuras OS para os mesmo equipamentos ja não iria precisar ter que digitar tudo de novo.
> 
> ![image](https://user-images.githubusercontent.com/53625745/116604333-5c64b800-a904-11eb-8dbe-b0816e1a2c96.png)
> 
> Campos necessários:
> 
> EQUIPAMENTO:
> MARCA: Isso ja tem lá
> MODELO:
> NÚMERO DE SÉRIE: ja tem lá
> PROCESSADOR:
> PLACA DE VÍDEO:
> RAM:
> HD / SSD:
> SISTEMA OPERACIONAL:
> SERIGRAFIA DA PLACA MÃE:
> TEM SENHA?:
> PRECISA DE BACKUP?:
> DEIXOU ALGUM ACESSÓRIO?:
> 
> Esse campo Descrição Produto/Serviço poderia ser desabilitado com essas opções ou deixa ele ai sem uso.

o campo "Descrição Produto/Serviço" esse não pode ser removido pois e nele que e informado em pesquisa e na msg do WhatsApp o campo "Descrição"

Ex: na msg "Sua **O.S 183** referente ao equipamento **PS3 SLIM** foi atualizada para Contato sem Sucesso"

o **PS3 SLIM** e oque esta no campo "Descrição Produto/Serviço"

e sobre 

> EQUIPAMENTO:
> MODELO:
> PROCESSADOR:
> PLACA DE VÍDEO:
> RAM:
> HD / SSD:
> SISTEMA OPERACIONAL:
> SERIGRAFIA DA PLACA MÃE:
> TEM SENHA?:
> PRECISA DE BACKUP?:
> DEIXOU ALGUM ACESSÓRIO?:

vc usa o campo "Observações"
creio que ficaria muito poluido ter todos esses campos pois pode ser que o usuario seja de outro ramo e ele não ira utilizar os campos

**Comment by brtechst** [comment]
Entendi seu posicionamento e você tem razão, como o sistemas não é feito só para uma função fica complicado deixar ele padrão para vários segmentos.

vou deixar os textos fixados por padrão dentro do campo observações.
