### ISSUE TITLE
NÃO É BUG - A opção de envio de e-mails foi desativada na sua versão?

### ISSUE THREAD

**Issue by brtechst** [hoshikawakun/MasterOS#11]
Não acho nada relacionado no sistema.

**Comment by hoshikawakun** [comment]
> 
> 
> Não acho nada relacionado no sistema.

Eu desativei pois para uso pessoal não axei necessário
Mas caso deseje re-ativar e bem simples
navegue ate a seguinte pasta 
"application>views>tema"
Abra o arquivo "menu.php"
e apague a linha "151" e depois a linha "144"

Agora navegue ate a pasta "application>views>mapos"
Abra o arquivo "configurar.php"
e apague na linha "26" os seguintes dados "`<!--`" e "`-->`"

**Comment by brtechst** [comment]
Mano gosto de você porque você detalha bem certinho as coisas, to empolgado com esse teu projeto por favor não para.

Estava com o Mapos versão mais nova instalada mas gostei mais das suas modificações e vou o usar o teu pois não sei como add as implementações do mapos na sua.

Por favor continua atualizando essa versão....
