### ISSUE TITLE
Nao consigo alterar logo termica

### ISSUE THREAD

**Issue by naodoubuff** [hoshikawakun/MasterOS#12]
Boa noite, estou com um problema, baixei o sistema, instalei o sistema do 0. Após finalizar a instalação o sistema nao abre. só copiando a pasta vendor do antigo Mapos que está no meu hostgator.

Outro problema que notei, é que nao consigo alterar a logo termica. Sempre da esse erro.
![image](https://user-images.githubusercontent.com/78187809/116958267-5eb27380-ac70-11eb-94f3-3a367f8ce112.png)

**Comment by brtechst** [comment]
Acredito que você tenha que excluir o Banco de dados e refazer a instalação.
