### ISSUE TITLE
Manutenção de arquivos

### ISSUE THREAD

**Issue by roviglio** [hoshikawakun/MasterOS#15]
gostaria de usar a sua versão no lugar do mapos (Anexo nas os )pois usa todos ao aquivos e não de erro na  os.
Mas ao incluir os comandos tive algunsa erros.
inclui o arquivo mas não visualiaza,
não faz o donldoad dem zip correto 
não mostra as figuras tipo tumps,  se tiver algo que possa me passar estou acrescentando digo tentando acrescentar na versão 4.50 o cadastro de equipamento ja esta rodando. se tiver interesse te manho os fontes. com a versao do mapos 4.35.0
Desde ja obrigado
ha do banco de dados do cadastro de cliente tem um cambo para url de fotos do cliente você ja imprementou isso?

**Comment by hoshikawakun** [comment]
> 
> 
> gostaria de usar a sua versão no lugar do mapos (Anexo nas os )pois usa todos ao aquivos e não de erro na os. Mas ao incluir os comandos tive algunsa erros. inclui o arquivo mas não visualiaza, não faz o donldoad dem zip correto não mostra as figuras tipo tumps, se tiver algo que possa me passar estou acrescentando digo tentando acrescentar na versão 4.50 o cadastro de equipamento ja esta rodando. se tiver interesse te manho os fontes. com a versao do mapos 4.35.0 Desde ja obrigado ha do banco de dados do cadastro de cliente tem um cambo para url de fotos do cliente você ja imprementou isso?

O meu sistema tem muitas modificações logo algum recurso pode ser que seja complicado de ser importado para o MapOS se não editar cada campo como se precisa]

sobre cliente com foto no cadastro, eu tentei implementar mas não obtive sucesso, mas acabei por deixar os campos na DB
