### ISSUE TITLE
Foto no cadastro de cliente

### ISSUE THREAD

**Issue by roviglio** [hoshikawakun/MasterOS#16]
vi no baco de dados um url foto no cadastr de cliente você ja implementou issso:? pode disponibilizar

**Comment by hoshikawakun** [comment]
> 
> 
> vi no baco de dados um url foto no cadastr de cliente você ja implementou issso:? pode disponibilizar

tem o campo no DB no cadastro de clientes pois tentei implementar foto do usuario mas não obtive sucesso, mas acabei por deixar o campo na DB
