### ISSUE TITLE
Erro na Tela De Login

### ISSUE THREAD

**Issue by smigou31** [hoshikawakun/MasterOS#21]
Após a instalação que ocorre normalmente, vai para a tela de login. Porém quando coloco dados da um erro: 
**A conta do usuário está expirada, por favor entre em contato com o administrador do sistema**

Como posso resolver esse problema ?

**Comment by hoshikawakun** [comment]
> Após a instalação que ocorre normalmente, vai para a tela de login. Porém quando coloco dados da um erro: **A conta do usuário está expirada, por favor entre em contato com o administrador do sistema**
> 
> Como posso resolver esse problema ?

Para resolver esse problema, ao instalar o sistema a data de vencimento coloque qualquer dada no ano 3000
