### ISSUE TITLE
Solicitação de Melhorias

### ISSUE THREAD

**Issue by Welder01** [hoshikawakun/MasterOS#4]
Meu amigo, primeiramente parabéns, o sistema ficou fantástico, muito bem modificado, buscava algo neste sentido !

Gostaria de compartilhar com você duas coisas que podem ajudar na melhorias do projeto:

1 - o envio de e-mails ainda é bastante utilizado e não vi essa possibilidade do seu projeto.
2 - Através do log-in de cliente ao imprimir OS não aparece o QRCODE PIX para pagamento.
3 - Integração com GERENCIANET | PAGSEGURO | além de mercado pago.

Verifiquei um bug no mercado pago que não exclui cobranças ou se quer cancela, o seu foi corrigido isso ?

Ademais, o projeto esta fantástico !!!
Espero que veja com bons olhos, aguardo retorno, forte abraço !!
Qual coisa pode me acionar via mensagem:
https://wa.me/5531988413749

**Comment by hoshikawakun** [comment]
> 
> 
> Meu amigo, primeiramente parabéns, o sistema ficou fantástico, muito bem modificado, buscava algo neste sentido !
> 
> Gostaria de compartilhar com você duas coisas que podem ajudar na melhorias do projeto:
> 
> 1 - o envio de e-mails ainda é bastante utilizado e não vi essa possibilidade do seu projeto.
> 2 - Através do log-in de cliente ao imprimir OS não aparece o QRCODE PIX para pagamento.
> 3 - Integração com GERENCIANET | PAGSEGURO | além de mercado pago.
> 
> Verifiquei um bug no mercado pago que não exclui cobranças ou se quer cancela, o seu foi corrigido isso ?
> 
> Ademais, o projeto esta fantástico !!!
> Espero que veja com bons olhos, aguardo retorno, forte abraço !!
> Qual coisa pode me acionar via mensagem:
> https://wa.me/5531988413749

sobre os eMails

Eu desativei pois para uso pessoal não axei necessário
Mas caso deseje re-ativar e bem simples
navegue ate a seguinte pasta 
"application>views>tema"
Abra o arquivo "menu.php"
e apague a linha "151" e depois a linha "144"

Agora navegue ate a pasta "application>views>mapos"
Abra o arquivo "configurar.php"
e apague na linha "26" os seguintes dados "`<!--`" e "`-->`"

**Comment by hoshikawakun** [comment]
> Verifiquei um bug no mercado pago que não exclui cobranças ou se quer cancela, o seu foi corrigido isso ?

devo corrigir quando for corrigido no MapOS
