### ISSUE TITLE
Solicitação de atualização

### ISSUE THREAD

**Issue by FMRBR** [hoshikawakun/MasterOS#5]
Bom dia caro amigo....

vi suas alterações no projeto do Mapos e fiquei encantando com tanta atualizações que você fez... Se possivel gostaria de sua ajuda.. Qualquer coisa estou disposto a ajudar financeiramente também....

meu zap... 62981762463 Fábio

**Comment by hoshikawakun** [comment]
que ajudas vc esta procurando

> 
> 
> Bom dia caro amigo....
> 
> vi suas alterações no projeto do Mapos e fiquei encantando com tanta atualizações que você fez... Se possivel gostaria de sua ajuda.. Qualquer coisa estou disposto a ajudar financeiramente também....
> 
> meu zap... 62981762463 Fábio
