### ISSUE TITLE
Instalacao

### ISSUE THREAD

**Issue by neozinh** [hoshikawakun/MasterOS#6]
Boa tarde @hoshikawakun ! Criei o banco de dados e fiz a instalação mas quando tento abrir pelo endereço aparece que a pagina nao pode er exibida. Por favor vc pode me ajudar. Essas alterações que vc fez vão me ajudar muito aqui.

**Comment by hoshikawakun** [comment]
> 
> 
> Boa tarde @hoshikawakun instalei aki ta funcionando beleza e me ajudando muito. Por favor pode me ajudar a criar para fazer upload e visualizar foto em adicionarcliente e tb a habilitar para registrar a quantidade e data das entradas e saídas dos produtos? Por favor!

add foto dos clientes e uma implementação bem comlicada assim como a de Add foto em produto
