### ISSUE TITLE
Tem como liberar de novo a pasta INSTALL

### ISSUE THREAD

**Issue by brtechst** [hoshikawakun/MasterOS#7]
Estou com mesmo problema lá devido as modificações do BD e preciso da sua pasta install para resolver mas o link la no no projeto do Ramon ta fora.

![image](https://user-images.githubusercontent.com/53625745/116576938-68da1800-a8e6-11eb-9ec0-e955e414e6e4.png)

**Comment by hoshikawakun** [comment]
> 
> 
> Estou com mesmo problema lá devido as modificações do BD e preciso da sua pasta install para resolver mas o link la no no projeto do Ramon ta fora.
> 
> ![image](https://user-images.githubusercontent.com/53625745/116576938-68da1800-a8e6-11eb-9ec0-e955e414e6e4.png)

e só baixar a ultima Release que ja ira completa com a ultima DB e todos os arquivos
