### ISSUE TITLE
Erro para entrar no sistema após instalado.

### ISSUE THREAD

**Issue by brtechst** [hoshikawakun/MasterOS#8]
** Descreva o bug **
Uma descrição clara e concisa do que é o erro.

Estava dando usuário e senha errados, fui lá no BD e alterei mas mesmo assim não entra.

![image](https://user-images.githubusercontent.com/53625745/116578722-13066f80-a8e8-11eb-84dd-0673d01f7913.png)

Não importa o usuário que eu colocar la no BD só da essa MSG.

![image](https://user-images.githubusercontent.com/53625745/116578808-29acc680-a8e8-11eb-9d21-da110a5d5a53.png)

**Comment by brtechst** [comment]
Ja testei várias versões do PHP mas a atual deixei na 7.3

**Comment by hoshikawakun** [comment]
> 
> 
> ** Descreva o bug **
> Uma descrição clara e concisa do que é o erro.
> 
> Estava dando usuário e senha errados, fui lá no BD e alterei mas mesmo assim não entra.
> 
> ![image](https://user-images.githubusercontent.com/53625745/116578722-13066f80-a8e8-11eb-84dd-0673d01f7913.png)
> 
> Não importa o usuário que eu colocar la no BD só da essa MSG.
> 
> ![image](https://user-images.githubusercontent.com/53625745/116578808-29acc680-a8e8-11eb-9d21-da110a5d5a53.png)

tente reinstalar o sistema do Zero, pode ser que tenha ocorrido algum erro durante a instalação
