### ISSUE TITLE
Não consigo cadastrar os Equipamentos

### ISSUE THREAD

**Issue by brtechst** [hoshikawakun/MasterOS#9]
![image](https://user-images.githubusercontent.com/53625745/116593609-a5fad600-a8f7-11eb-9b82-00b06f41363f.png)

Se eu tentar cadastrar só da esse erro.

o que faço?

**Comment by hoshikawakun** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/53625745/116593609-a5fad600-a8f7-11eb-9b82-00b06f41363f.png)
> 
> Se eu tentar cadastrar só da esse erro.
> 
> o que faço?

Acabei de testar aki e esta funcionando perfeitamente
se continuar o erro me avise

**Comment by brtechst** [comment]
Se eu upar novamente a sua BD dentro la da que ja foi criada será que não resolveria?

**Comment by hoshikawakun** [comment]
> Se eu upar novamente a sua BD dentro la da que ja foi criada será que não resolveria?

Só vai funcionar se reinstalar o sistema do zero, se mesmo assim não funcionar me avise para eu verificar aki

**Comment by brtechst** [comment]
![image](https://user-images.githubusercontent.com/53625745/116715465-216a8f00-a9ad-11eb-87cd-4ab9c8f36f5a.png)

Segue imagens do BD, acredito que a importação foi feita corretamente.

**Comment by hoshikawakun** [comment]
> Reinstalei usando os arquivos que você disponibilizou + o restante dos arquivos do Mapos original.
> 
> Problema continuou.
> 
> quer um print de alguma parte do BD?

Tá aí o problema, não vai funcionar se vc mesclar os sistemas devido às varias alterações entre eles, faça uma instalação do zero usando a última release do MasterOS

**Comment by brtechst** [comment]
Mas a sua última versão não tem tudo para fazer a instalação.

as pastas quem tem lá não são suficientes para a instalação ai tive que pegar o restante do Mapos.

**Comment by brtechst** [comment]
Na tua só tem isso...

![image](https://user-images.githubusercontent.com/53625745/116719988-0fd7b600-a9b2-11eb-92f5-0e9067b7afa4.png)

**Comment by brtechst** [comment]
Resolvido!

Eu estava usando uma release antiga, baixei a mais nova e reinstalei do zero e resolveu.

obrigado @hoshikawakun
